import type { JsonValue, RpcContractDescriptor, RpcMethodDescriptor, RpcServiceDescriptor } from "./types";
import { canonicalizeDescriptor, validateRpcContractDescriptor } from "./descriptor";

export { canonicalizeDescriptor } from "./descriptor";

export interface TypeScriptGeneratorOptions {
  readonly moduleSpecifier?: string;
}

export function generateTypeScriptBindings(
  descriptor: RpcContractDescriptor,
  options: TypeScriptGeneratorOptions = {},
): string {
  validateRpcContractDescriptor(descriptor);
  const moduleSpecifier = options.moduleSpecifier ?? "@sunder/sdk";
  const output: string[] = [
    "// <auto-generated />",
    `import type { JsonValue, RpcCallOptions, RpcClient, RpcInvocationContext } from ${JSON.stringify(moduleSpecifier)};`,
    "",
  ];
  const definitions = descriptor.$defs;
  for (const name of Object.keys(definitions).sort(ordinal)) {
    const schema = definitions[name];
    if (schema !== undefined) emitDefinition(output, name, schema, definitions);
  }
  for (const service of services(descriptor.services).sort((left, right) => ordinal(left.serviceId, right.serviceId))) {
    emitService(output, service, definitions);
  }
  return `${output.join("\n").replace(/\r\n/gu, "\n")}\n`;
}

function emitDefinition(
  output: string[],
  definitionName: string,
  schema: Readonly<Record<string, JsonValue>>,
  definitions: Readonly<Record<string, Readonly<Record<string, JsonValue>>>>,
): void {
  if (schema.type !== "object" || !isObject(schema.properties)) return;
  const required = new Set(Array.isArray(schema.required) ? schema.required.filter((value): value is string => typeof value === "string") : []);
  output.push(`export interface ${identifier(definitionName)} {`);
  for (const propertyName of Object.keys(schema.properties).sort(ordinal)) {
    const propertySchema = schema.properties[propertyName];
    if (!isObject(propertySchema)) continue;
    output.push(`  readonly ${propertyIdentifier(propertyName)}${required.has(propertyName) ? "" : "?"}: ${typeName(propertySchema, definitions)};`);
  }
  output.push("}", "");
}

function emitService(
  output: string[],
  service: RpcServiceDescriptor,
  definitions: Readonly<Record<string, Readonly<Record<string, JsonValue>>>>,
): void {
  const serviceName = identifier(service.serviceId);
  const orderedMethods = methods(service.methods).sort((left, right) => ordinal(left.methodId, right.methodId));
  output.push(`export interface I${serviceName}Provider {`);
  for (const method of orderedMethods) {
    const request = referenceType(schemaReference(method.requestSchema), definitions);
    const result = referenceType(schemaReference(method.kind === "unary" ? method.responseSchema : method.eventSchema), definitions);
    const returnType = method.kind === "unary" ? `Promise<${result}>` : `AsyncIterable<${result}>`;
    output.push(`  ${identifier(method.methodId)}(request: ${request}, context: RpcInvocationContext): ${returnType};`);
  }
  output.push("}", "", `export class ${serviceName}Client {`, "  readonly #client: RpcClient;", "  readonly #endpointReference: string;", "", `  public constructor(client: RpcClient, endpointReference: string) {`, "    this.#client = client;", "    this.#endpointReference = endpointReference;", "  }", "");
  for (const method of orderedMethods) {
    const request = referenceType(schemaReference(method.requestSchema), definitions);
    const result = referenceType(schemaReference(method.kind === "unary" ? method.responseSchema : method.eventSchema), definitions);
    const returnType = method.kind === "unary" ? `Promise<${result}>` : `AsyncIterable<${result}>`;
    const operation = method.kind === "unary" ? "invoke" : "subscribe";
    output.push(
      `  public ${identifier(method.methodId)}(request: ${request}, options?: RpcCallOptions): ${returnType} {`,
      `    return this.#client.${operation}<${request}, ${result}>(this.#endpointReference, ${JSON.stringify(service.serviceId)}, ${JSON.stringify(method.methodId)}, request, options);`,
      "  }",
      "",
    );
  }
  output.push("}", "");
}

function typeName(
  schema: Readonly<Record<string, JsonValue>>,
  definitions: Readonly<Record<string, Readonly<Record<string, JsonValue>>>>,
): string {
  if (typeof schema.$ref === "string") return referenceType(schema.$ref, definitions);
  if (Array.isArray(schema.oneOf)) return "JsonValue";
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return isObject(schema.items) ? `readonly ${typeName(schema.items, definitions)}[]` : "readonly JsonValue[]";
    case "object":
      return isObject(schema.additionalProperties)
        ? `Readonly<Record<string, ${typeName(schema.additionalProperties, definitions)}>>`
        : "JsonValue";
    default:
      return "JsonValue";
  }
}

function referenceType(
  reference: string,
  definitions: Readonly<Record<string, Readonly<Record<string, JsonValue>>>>,
): string {
  const prefix = "#/$defs/";
  if (!reference.startsWith(prefix)) return "JsonValue";
  let name = reference.slice(prefix.length);
  let schema = definitions[name];
  const visited = new Set<string>();
  while (schema !== undefined && typeof schema.$ref === "string" && schema.$ref.startsWith(prefix)) {
    if (!visited.add(name)) return "JsonValue";
    name = schema.$ref.slice(prefix.length);
    schema = definitions[name];
  }
  if (schema === undefined) return "JsonValue";
  return schema.type === "object" && isObject(schema.properties) ? identifier(name) : typeName(schema, definitions);
}

function schemaReference(value: RpcMethodDescriptor["requestSchema"] | undefined): string {
  if (typeof value === "string") return value;
  if (value !== undefined && typeof value.$ref === "string") return value.$ref;
  throw new TypeError("RPC method schema must be a local definition reference.");
}

function services(value: RpcContractDescriptor["services"]): RpcServiceDescriptor[] {
  return Array.isArray(value)
    ? [...value]
    : Object.entries(value).map(([serviceId, service]) => ({ ...service, serviceId }));
}

function methods(value: RpcServiceDescriptor["methods"]): RpcMethodDescriptor[] {
  return Array.isArray(value)
    ? [...value]
    : Object.entries(value).map(([methodId, method]) => ({ ...method, methodId }));
}

function identifier(value: string): string {
  let output = "";
  let capitalize = true;
  for (const character of value) {
    if (!/[A-Za-z0-9]/u.test(character)) {
      capitalize = true;
      continue;
    }
    output += capitalize ? character.toUpperCase() : character;
    capitalize = false;
  }
  if (output.length === 0) output = "Value";
  if (/^[0-9]/u.test(output)) output = `_${output}`;
  return output;
}

function propertyIdentifier(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value) ? value : JSON.stringify(value);
}

function isObject(value: unknown): value is Readonly<Record<string, JsonValue>> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function ordinal(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}
