<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\Host\Sunder.Host.Supervisor\Sunder.Host.Supervisor.csproj" />
    <ProjectReference Include="..\..\src\Host\Sunder.Runtime.Host\Sunder.Runtime.Host.csproj" />
  </ItemGroup>

</Project>
