<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sunder.Sdk" Version="SUNDER_TEMPLATE_PACKAGE_VERSION_RANGE" />
    <PackageReference Include="Sunder.Package.Build" Version="SUNDER_TEMPLATE_PACKAGE_VERSION_RANGE" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sunder.Package.Template.Contracts\Sunder.Package.Template.Contracts.csproj"
                      Condition="Exists('..\Sunder.Package.Template.Contracts\Sunder.Package.Template.Contracts.csproj')" />
    <ProjectReference Include="Sunder.Package.Template.Contracts\Sunder.Package.Template.Contracts.csproj"
                      Condition="Exists('Sunder.Package.Template.Contracts\Sunder.Package.Template.Contracts.csproj')" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**\*.Contracts\**\*.cs" />
  </ItemGroup>

  <Import Project="HostContracts.PackageReferences.props" />
  <Import Project="Avalonia.PackageReferences.props" Condition="Exists('Avalonia.PackageReferences.props')" />
  <Import Project="Stacks.PackageReferences.props" Condition="Exists('Stacks.PackageReferences.props')" />

</Project>
