<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <Version>$(SunderDeveloperPackageVersion)</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
    <Title>Sunder.Sdk.Avalonia</Title>
    <Authors>Younics</Authors>
    <PackageProjectUrl>https://sunderapp.io</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Younics/sunder-core</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sunder.Sdk\Sunder.Sdk.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Sunder.Sdk\icon.png" Link="icon.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="..\Sunder.Sdk\LICENSE" Link="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
