using System.Text;
using System.Text.Json;
using Sunder.Sdk.Compatibility;

namespace Sunder.Sdk.Rpc;

/// <summary>Emits deterministic DTO, caller-scope clients, and provider adapters from an RPC descriptor.</summary>
/// <remarks>The generator is intentionally dependency-free so build tooling may host it in-process.</remarks>
[SunderSdkCapability(SunderSdkCapabilities.RpcV1)]
public static class SunderRpcCSharpGenerator
{
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while", "add", "alias", "and", "ascending", "async", "await", "by",
        "descending", "dynamic", "equals", "file", "from", "get", "global", "group", "init", "into",
        "join", "let", "managed", "nameof", "not", "notnull", "on", "or", "orderby", "partial",
        "record", "remove", "required", "scoped", "select", "set", "unmanaged", "value", "var", "when",
        "where", "with", "yield",
    };

    /// <summary>Generates one deterministic C# source file for a validated descriptor.</summary>
    public static string Generate(SunderRpcContractDescriptor descriptor, string namespaceName)
    {
        ArgumentNullException.ThrowIfNull(descriptor);
        if (!IsNamespace(namespaceName))
        {
            throw new ArgumentException("The generated C# namespace is invalid.", nameof(namespaceName));
        }

        var model = BuildModel(descriptor);
        var output = new StringBuilder();
        output.AppendLine("// <auto-generated />");
        output.AppendLine("#nullable enable");
        output.AppendLine("using System;");
        output.AppendLine("using System.Collections.Generic;");
        output.AppendLine("using System.Runtime.CompilerServices;");
        output.AppendLine("using System.Text.Json;");
        output.AppendLine("using System.Text.Json.Serialization;");
        output.AppendLine("using System.Threading;");
        output.AppendLine("using System.Threading.Tasks;");
        output.AppendLine("using Sunder.Sdk.Rpc;");
        output.Append("namespace ").Append(EscapeNamespace(namespaceName)).AppendLine(";").AppendLine();

        foreach (var definition in model.Definitions)
        {
            EmitDefinition(output, definition, model);
        }
        foreach (var service in model.Services)
        {
            EmitService(output, service, model);
        }
        EmitHandler(output, model);
        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static GeneratorModel BuildModel(SunderRpcContractDescriptor descriptor)
    {
        var topLevelNames = new SymbolAllocator();
        var recordNames = new Dictionary<string, string>(StringComparer.Ordinal);
        var definitions = new List<DefinitionModel>();
        foreach (var definition in descriptor.Definitions.OrderBy(static item => item.Key, StringComparer.Ordinal))
        {
            if (!IsRecordSchema(definition.Value)) continue;
            var typeName = topLevelNames.Allocate(Identifier(definition.Key));
            recordNames.Add(definition.Key, typeName);
            definitions.Add(new DefinitionModel(definition.Key, typeName, definition.Value));
        }

        var services = new List<ServiceModel>();
        foreach (var service in descriptor.Services.OrderBy(static item => item.ServiceId, StringComparer.Ordinal))
        {
            var stem = Identifier(service.ServiceId);
            var providerTypeName = topLevelNames.Allocate("I" + stem + "Provider");
            var clientTypeName = topLevelNames.Allocate(stem + "Client");
            var methodNames = new SymbolAllocator();
            var methods = service.Methods.OrderBy(static item => item.MethodId, StringComparer.Ordinal)
                .Select(method => new MethodModel(method, methodNames.Allocate(Identifier(method.MethodId) + "Async")))
                .ToArray();
            services.Add(new ServiceModel(service, providerTypeName, clientTypeName, methods));
        }

        var handlerTypeName = topLevelNames.Allocate(Identifier(descriptor.ContractId) + "RpcHandler");
        return new GeneratorModel(descriptor.Definitions, recordNames, definitions, services, handlerTypeName);
    }

    private static void EmitDefinition(
        StringBuilder output,
        DefinitionModel definition,
        GeneratorModel model)
    {
        var properties = definition.Schema.GetProperty("properties");
        var required = definition.Schema.TryGetProperty("required", out var requiredElement)
            ? requiredElement.EnumerateArray().Select(static item => item.GetString()!).ToHashSet(StringComparer.Ordinal)
            : new HashSet<string>(StringComparer.Ordinal);
        var propertyNames = new SymbolAllocator();
        propertyNames.Reserve(definition.TypeName);

        output.Append("public sealed class ").Append(definition.TypeName).AppendLine().AppendLine("{");
        foreach (var property in properties.EnumerateObject().OrderBy(static item => item.Name, StringComparer.Ordinal))
        {
            var propertyType = GetTypeName(property.Value, model);
            var isRequired = required.Contains(property.Name);
            output.Append("    [JsonPropertyName(\"").Append(EscapeStringLiteral(property.Name)).AppendLine("\")]");
            if (!isRequired)
            {
                output.AppendLine("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
                propertyType = MakeNullable(propertyType);
            }
            output.Append("    public ");
            if (isRequired) output.Append("required ");
            output.Append(propertyType).Append(' ')
                .Append(propertyNames.Allocate(Identifier(property.Name)))
                .AppendLine(" { get; init; }")
                .AppendLine();
        }
        output.AppendLine("}").AppendLine();
    }

    private static void EmitService(
        StringBuilder output,
        ServiceModel service,
        GeneratorModel model)
    {
        output.Append("public interface ").Append(service.ProviderTypeName).AppendLine().AppendLine("{");
        foreach (var method in service.Methods)
        {
            var requestType = ReferenceType(method.Descriptor.RequestSchemaReference, model);
            var outputType = ReferenceType(method.Descriptor.OutputSchemaReference, model);
            output.Append("    ");
            if (method.Descriptor.Kind == SunderRpcMethodKind.Unary)
            {
                output.Append("ValueTask<").Append(outputType).Append("> ");
            }
            else
            {
                output.Append("IAsyncEnumerable<").Append(outputType).Append("> ");
            }
            output.Append(method.MethodName).Append("(SunderRpcInvocationContext context, ")
                .Append(requestType)
                .AppendLine(" request, CancellationToken cancellationToken = default);");
        }
        output.AppendLine("}").AppendLine();

        output.Append("public sealed class ").Append(service.ClientTypeName).AppendLine().AppendLine("{");
        output.AppendLine("    private readonly ISunderRpcCallScope _scope;");
        output.AppendLine("    private readonly SunderRpcEndpointReference _endpoint;").AppendLine();
        output.Append("    public ").Append(service.ClientTypeName)
            .AppendLine("(ISunderRpcCallScope scope, SunderRpcEndpointReference endpoint)")
            .AppendLine("    {")
            .AppendLine("        _scope = scope ?? throw new ArgumentNullException(nameof(scope));")
            .AppendLine("        _endpoint = endpoint ?? throw new ArgumentNullException(nameof(endpoint));")
            .AppendLine("    }").AppendLine();
        foreach (var method in service.Methods)
        {
            var requestType = ReferenceType(method.Descriptor.RequestSchemaReference, model);
            var outputType = ReferenceType(method.Descriptor.OutputSchemaReference, model);
            output.Append("    public ");
            if (method.Descriptor.Kind == SunderRpcMethodKind.Unary)
            {
                output.Append("ValueTask<").Append(outputType).Append("> ");
            }
            else
            {
                output.Append("IAsyncEnumerable<").Append(outputType).Append("> ");
            }
            output.Append(method.MethodName).Append('(').Append(requestType)
                .Append(" request, CancellationToken cancellationToken = default)").AppendLine()
                .Append("        => _scope.")
                .Append(method.Descriptor.Kind == SunderRpcMethodKind.Unary ? "InvokeAsync" : "SubscribeAsync")
                .Append('<').Append(requestType).Append(", ").Append(outputType).Append(">(_endpoint, \"")
                .Append(EscapeStringLiteral(service.Descriptor.ServiceId)).Append("\", \"")
                .Append(EscapeStringLiteral(method.Descriptor.MethodId))
                .AppendLine("\", request, cancellationToken: cancellationToken);")
                .AppendLine();
        }
        output.AppendLine("}").AppendLine();
    }

    private static void EmitHandler(StringBuilder output, GeneratorModel model)
    {
        output.Append("public sealed class ").Append(model.HandlerTypeName)
            .AppendLine(" : ISunderRpcServiceHandler").AppendLine("{");
        output.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)")
            .AppendLine("    {")
            .AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,")
            .AppendLine("        PropertyNameCaseInsensitive = false,")
            .AppendLine("        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,")
            .AppendLine("    };");
        for (var index = 0; index < model.Services.Count; index++)
        {
            output.Append("    private readonly ").Append(model.Services[index].ProviderTypeName)
                .Append(" _service").Append(index + 1).AppendLine(";");
        }
        output.AppendLine();
        output.Append("    public ").Append(model.HandlerTypeName).Append('(');
        for (var index = 0; index < model.Services.Count; index++)
        {
            if (index > 0) output.Append(", ");
            output.Append(model.Services[index].ProviderTypeName).Append(" service").Append(index + 1);
        }
        output.AppendLine(")").AppendLine("    {");
        for (var index = 0; index < model.Services.Count; index++)
        {
            output.Append("        _service").Append(index + 1).Append(" = service").Append(index + 1)
                .Append(" ?? throw new ArgumentNullException(nameof(service").Append(index + 1).AppendLine("));");
        }
        output.AppendLine("    }").AppendLine();

        output.AppendLine("    public ValueTask<JsonElement> InvokeUnaryAsync(")
            .AppendLine("        SunderRpcInvocationContext context,")
            .AppendLine("        string serviceId,")
            .AppendLine("        string methodId,")
            .AppendLine("        JsonElement request,")
            .AppendLine("        CancellationToken cancellationToken = default)")
            .AppendLine("    {");
        for (var serviceIndex = 0; serviceIndex < model.Services.Count; serviceIndex++)
        {
            var service = model.Services[serviceIndex];
            foreach (var method in service.Methods.Where(static item => item.Descriptor.Kind == SunderRpcMethodKind.Unary))
            {
                var requestType = ReferenceType(method.Descriptor.RequestSchemaReference, model);
                output.Append("        if (string.Equals(serviceId, \"")
                    .Append(EscapeStringLiteral(service.Descriptor.ServiceId))
                    .Append("\", StringComparison.Ordinal) && string.Equals(methodId, \"")
                    .Append(EscapeStringLiteral(method.Descriptor.MethodId))
                    .AppendLine("\", StringComparison.Ordinal))")
                    .AppendLine("        {")
                    .Append("            return SerializeUnaryAsync(_service").Append(serviceIndex + 1).Append('.')
                    .Append(method.MethodName).Append("(context, Deserialize<").Append(requestType)
                    .AppendLine(">(request), cancellationToken));")
                    .AppendLine("        }");
            }
        }
        output.AppendLine("        return ValueTask.FromException<JsonElement>(UnknownMethod(serviceId, methodId, \"unary\"));")
            .AppendLine("    }").AppendLine();

        output.AppendLine("    public IAsyncEnumerable<JsonElement> InvokeServerStreamAsync(")
            .AppendLine("        SunderRpcInvocationContext context,")
            .AppendLine("        string serviceId,")
            .AppendLine("        string methodId,")
            .AppendLine("        JsonElement request,")
            .AppendLine("        CancellationToken cancellationToken = default)")
            .AppendLine("    {");
        for (var serviceIndex = 0; serviceIndex < model.Services.Count; serviceIndex++)
        {
            var service = model.Services[serviceIndex];
            foreach (var method in service.Methods.Where(static item => item.Descriptor.Kind == SunderRpcMethodKind.ServerStream))
            {
                var requestType = ReferenceType(method.Descriptor.RequestSchemaReference, model);
                output.Append("        if (string.Equals(serviceId, \"")
                    .Append(EscapeStringLiteral(service.Descriptor.ServiceId))
                    .Append("\", StringComparison.Ordinal) && string.Equals(methodId, \"")
                    .Append(EscapeStringLiteral(method.Descriptor.MethodId))
                    .AppendLine("\", StringComparison.Ordinal))")
                    .AppendLine("        {")
                    .Append("            return SerializeStream(_service").Append(serviceIndex + 1).Append('.')
                    .Append(method.MethodName).Append("(context, Deserialize<").Append(requestType)
                    .AppendLine(">(request), cancellationToken), cancellationToken);")
                    .AppendLine("        }");
            }
        }
        output.AppendLine("        return ThrowStream(UnknownMethod(serviceId, methodId, \"server-stream\"), cancellationToken);")
            .AppendLine("    }").AppendLine();

        output.AppendLine("    private static async ValueTask<JsonElement> SerializeUnaryAsync<T>(ValueTask<T> response)")
            .AppendLine("        where T : notnull")
            .AppendLine("        => JsonSerializer.SerializeToElement(await response.ConfigureAwait(false), JsonOptions);")
            .AppendLine();
        output.AppendLine("    private static T Deserialize<T>(JsonElement value)")
            .AppendLine("        where T : notnull")
            .AppendLine("        => value.Deserialize<T>(JsonOptions)")
            .AppendLine("           ?? throw new InvalidOperationException(\"A validated RPC request deserialized to null.\");")
            .AppendLine();
        output.AppendLine("    private static async IAsyncEnumerable<JsonElement> SerializeStream<T>(")
            .AppendLine("        IAsyncEnumerable<T> source,")
            .AppendLine("        [EnumeratorCancellation] CancellationToken cancellationToken)")
            .AppendLine("        where T : notnull")
            .AppendLine("    {")
            .AppendLine("        await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))")
            .AppendLine("        {")
            .AppendLine("            yield return JsonSerializer.SerializeToElement(item, JsonOptions);")
            .AppendLine("        }")
            .AppendLine("    }").AppendLine();
        output.AppendLine("    private static async IAsyncEnumerable<JsonElement> ThrowStream(")
            .AppendLine("        Exception exception,")
            .AppendLine("        [EnumeratorCancellation] CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        cancellationToken.ThrowIfCancellationRequested();")
            .AppendLine("        await Task.CompletedTask;")
            .AppendLine("        throw exception;")
            .AppendLine("#pragma warning disable CS0162")
            .AppendLine("        yield break;")
            .AppendLine("#pragma warning restore CS0162")
            .AppendLine("    }").AppendLine();
        output.AppendLine("    private static Exception UnknownMethod(string serviceId, string methodId, string kind)")
            .AppendLine("        => new InvalidOperationException($\"RPC provider adapter does not implement {kind} method '{serviceId}/{methodId}'.\");")
            .AppendLine("}").AppendLine();
    }

    private static string GetTypeName(JsonElement schema, GeneratorModel model)
    {
        if (schema.TryGetProperty("$ref", out var reference))
        {
            return ReferenceType(reference.GetString()!, model);
        }
        if (schema.TryGetProperty("oneOf", out var oneOf))
        {
            var variants = oneOf.EnumerateArray().ToArray();
            if (variants.Length == 2)
            {
                var nullCount = variants.Count(static variant =>
                    variant.TryGetProperty("type", out var type) && type.GetString() == "null");
                if (nullCount == 1)
                {
                    var valueSchema = variants.Single(static variant =>
                        !variant.TryGetProperty("type", out var type) || type.GetString() != "null");
                    return MakeNullable(GetTypeName(valueSchema, model));
                }
            }
            return "JsonElement";
        }

        return schema.GetProperty("type").GetString() switch
        {
            "string" => "string",
            "integer" => "long",
            "number" => "decimal",
            "boolean" => "bool",
            "null" => "object?",
            "array" => "IReadOnlyList<" + GetTypeName(schema.GetProperty("items"), model) + ">",
            "object" when schema.GetProperty("additionalProperties").ValueKind == JsonValueKind.Object
                => "IReadOnlyDictionary<string, "
                   + GetTypeName(schema.GetProperty("additionalProperties"), model)
                   + ">",
            _ => "JsonElement",
        };
    }

    private static string ReferenceType(string reference, GeneratorModel model)
    {
        var name = reference["#/$defs/".Length..];
        var schema = model.Schemas[name];
        var visited = new HashSet<string>(StringComparer.Ordinal);
        while (schema.TryGetProperty("$ref", out var nestedReference))
        {
            if (!visited.Add(name)) return "JsonElement";
            name = nestedReference.GetString()!["#/$defs/".Length..];
            schema = model.Schemas[name];
        }
        return model.RecordNames.TryGetValue(name, out var recordName)
            ? recordName
            : GetTypeName(schema, model);
    }

    private static bool IsRecordSchema(JsonElement schema)
        => schema.TryGetProperty("type", out var type)
           && type.GetString() == "object"
           && schema.TryGetProperty("properties", out _)
           && schema.GetProperty("additionalProperties").ValueKind == JsonValueKind.False;

    private static string MakeNullable(string typeName)
        => typeName.EndsWith("?", StringComparison.Ordinal) ? typeName : typeName + "?";

    private static string Identifier(string value)
    {
        var output = new StringBuilder();
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsAsciiLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }
            output.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }
        if (output.Length == 0) output.Append("Value");
        if (char.IsAsciiDigit(output[0])) output.Insert(0, '_');
        return EscapeIdentifier(output.ToString());
    }

    private static string EscapeIdentifier(string value)
        => CSharpKeywords.Contains(value) ? "@" + value : value;

    private static string EscapeNamespace(string value)
        => string.Join('.', value.Split('.').Select(EscapeIdentifier));

    private static bool IsNamespace(string value)
        => !string.IsNullOrWhiteSpace(value)
           && value.Length <= 512
           && value.Split('.').All(static segment => segment.Length > 0
               && (char.IsAsciiLetter(segment[0]) || segment[0] == '_')
               && segment.All(static character => char.IsAsciiLetterOrDigit(character) || character == '_'));

    private static string EscapeStringLiteral(string value)
    {
        var output = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\': output.Append("\\\\"); break;
                case '"': output.Append("\\\""); break;
                case '\0': output.Append("\\0"); break;
                case '\a': output.Append("\\a"); break;
                case '\b': output.Append("\\b"); break;
                case '\f': output.Append("\\f"); break;
                case '\n': output.Append("\\n"); break;
                case '\r': output.Append("\\r"); break;
                case '\t': output.Append("\\t"); break;
                case '\v': output.Append("\\v"); break;
                default:
                    if (char.IsControl(character) || character is '\u2028' or '\u2029')
                    {
                        output.Append("\\u").Append(((int)character).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        output.Append(character);
                    }
                    break;
            }
        }
        return output.ToString();
    }

    private sealed class SymbolAllocator
    {
        private readonly HashSet<string> _used = new(StringComparer.Ordinal);

        public void Reserve(string value) => _used.Add(value);

        public string Allocate(string preferred)
        {
            preferred = EscapeIdentifier(preferred);
            if (_used.Add(preferred)) return preferred;
            var unescaped = preferred.StartsWith('@') ? preferred[1..] : preferred;
            for (var suffix = 2; ; suffix++)
            {
                var candidate = EscapeIdentifier(unescaped + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture));
                if (_used.Add(candidate)) return candidate;
            }
        }
    }

    private sealed record DefinitionModel(string Name, string TypeName, JsonElement Schema);

    private sealed record MethodModel(SunderRpcMethodDescriptor Descriptor, string MethodName);

    private sealed record ServiceModel(
        SunderRpcServiceDescriptor Descriptor,
        string ProviderTypeName,
        string ClientTypeName,
        IReadOnlyList<MethodModel> Methods);

    private sealed record GeneratorModel(
        IReadOnlyDictionary<string, JsonElement> Schemas,
        IReadOnlyDictionary<string, string> RecordNames,
        IReadOnlyList<DefinitionModel> Definitions,
        IReadOnlyList<ServiceModel> Services,
        string HandlerTypeName);
}
