using System.Text;
using System.Text.Json;
using Sunder.Sdk.Compatibility;

namespace Sunder.Sdk.Rpc;

/// <summary>Emits deterministic minimal DTO, client, and provider scaffolding from an RPC descriptor.</summary>
/// <remarks>The generator is intentionally dependency-free so build tooling may host it in-process.</remarks>
[SunderSdkCapability(SunderSdkCapabilities.RpcV1)]
public static class SunderRpcCSharpGenerator
{
    /// <summary>Generates one deterministic C# source file for a validated descriptor.</summary>
    public static string Generate(SunderRpcContractDescriptor descriptor, string namespaceName)
    {
        ArgumentNullException.ThrowIfNull(descriptor);
        if (!IsNamespace(namespaceName))
        {
            throw new ArgumentException("The generated C# namespace is invalid.", nameof(namespaceName));
        }

        var output = new StringBuilder();
        output.AppendLine("// <auto-generated />");
        output.AppendLine("#nullable enable");
        output.AppendLine("using System.Collections.Generic;");
        output.AppendLine("using System.Text.Json;");
        output.AppendLine("using System.Text.Json.Serialization;");
        output.AppendLine("using System.Threading;");
        output.AppendLine("using System.Threading.Tasks;");
        output.AppendLine("using Sunder.Sdk.Rpc;");
        output.Append("namespace ").Append(namespaceName).AppendLine(";").AppendLine();

        foreach (var definition in descriptor.Definitions.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
        {
            EmitDefinition(output, definition.Key, definition.Value, descriptor.Definitions);
        }
        foreach (var service in descriptor.Services.OrderBy(static service => service.ServiceId, StringComparer.Ordinal))
        {
            EmitService(output, service, descriptor.Definitions);
        }
        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void EmitDefinition(
        StringBuilder output,
        string definitionName,
        JsonElement schema,
        IReadOnlyDictionary<string, JsonElement> definitions)
    {
        if (!schema.TryGetProperty("type", out var type) || type.GetString() != "object"
            || !schema.TryGetProperty("properties", out var properties))
        {
            return;
        }

        var typeName = Identifier(definitionName);
        var required = schema.GetProperty("required").EnumerateArray()
            .Select(static item => item.GetString()!)
            .ToHashSet(StringComparer.Ordinal);
        output.Append("public sealed class ").Append(typeName).AppendLine().AppendLine("{");
        foreach (var property in properties.EnumerateObject().OrderBy(static property => property.Name, StringComparer.Ordinal))
        {
            var propertyType = GetTypeName(property.Value, definitions);
            var isRequired = required.Contains(property.Name);
            output.Append("    [JsonPropertyName(\"").Append(Escape(property.Name)).AppendLine("\")]");
            if (!isRequired) output.AppendLine("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
            output.Append("    public ").Append(propertyType);
            if (!isRequired && !propertyType.EndsWith("?", StringComparison.Ordinal)) output.Append('?');
            output.Append(' ').Append(Identifier(property.Name)).Append(" { get; init; }");
            if (isRequired && IsReferenceType(propertyType)) output.Append(" = default!;");
            output.AppendLine().AppendLine();
        }
        output.AppendLine("}").AppendLine();
    }

    private static void EmitService(
        StringBuilder output,
        SunderRpcServiceDescriptor service,
        IReadOnlyDictionary<string, JsonElement> definitions)
    {
        var serviceName = Identifier(service.ServiceId);
        output.Append("public interface I").Append(serviceName).AppendLine("Provider").AppendLine("{");
        foreach (var method in service.Methods.OrderBy(static method => method.MethodId, StringComparer.Ordinal))
        {
            var requestType = ReferenceType(method.RequestSchemaReference, definitions);
            var outputType = ReferenceType(method.OutputSchemaReference, definitions);
            output.Append("    ");
            if (method.Kind == SunderRpcMethodKind.Unary)
            {
                output.Append("ValueTask<").Append(outputType).Append("> ");
            }
            else
            {
                output.Append("IAsyncEnumerable<").Append(outputType).Append("> ");
            }
            output.Append(Identifier(method.MethodId)).Append("Async(")
                .Append(requestType).Append(" request, CancellationToken cancellationToken = default);").AppendLine();
        }
        output.AppendLine("}").AppendLine();

        output.Append("public sealed class ").Append(serviceName).AppendLine("Client").AppendLine("{");
        output.AppendLine("    private readonly ISunderRpcClient _client;");
        output.AppendLine("    private readonly SunderRpcEndpointReference _endpoint;").AppendLine();
        output.Append("    public ").Append(serviceName)
            .AppendLine("Client(ISunderRpcClient client, SunderRpcEndpointReference endpoint)")
            .AppendLine("    {")
            .AppendLine("        _client = client;")
            .AppendLine("        _endpoint = endpoint;")
            .AppendLine("    }").AppendLine();
        foreach (var method in service.Methods.OrderBy(static method => method.MethodId, StringComparer.Ordinal))
        {
            var requestType = ReferenceType(method.RequestSchemaReference, definitions);
            var outputType = ReferenceType(method.OutputSchemaReference, definitions);
            output.Append("    public ");
            if (method.Kind == SunderRpcMethodKind.Unary)
            {
                output.Append("ValueTask<").Append(outputType).Append("> ");
            }
            else
            {
                output.Append("IAsyncEnumerable<").Append(outputType).Append("> ");
            }
            output.Append(Identifier(method.MethodId)).Append("Async(")
                .Append(requestType).Append(" request, CancellationToken cancellationToken = default)").AppendLine()
                .Append("        => _client.")
                .Append(method.Kind == SunderRpcMethodKind.Unary ? "InvokeAsync" : "SubscribeAsync")
                .Append('<').Append(requestType).Append(", ").Append(outputType).Append(">(_endpoint, \"")
                .Append(Escape(service.ServiceId)).Append("\", \"").Append(Escape(method.MethodId))
                .AppendLine("\", request, cancellationToken: cancellationToken);").AppendLine();
        }
        output.AppendLine("}").AppendLine();
    }

    private static string GetTypeName(
        JsonElement schema,
        IReadOnlyDictionary<string, JsonElement> definitions)
    {
        if (schema.TryGetProperty("$ref", out var reference))
        {
            return ReferenceType(reference.GetString()!, definitions);
        }
        if (schema.TryGetProperty("oneOf", out var oneOf))
        {
            var variants = oneOf.EnumerateArray().ToArray();
            if (variants.Length == 2)
            {
                var nullCount = variants.Count(static variant =>
                    variant.TryGetProperty("type", out var type) && type.GetString() == "null");
                if (nullCount == 1)
                {
                    var valueSchema = variants.Single(static variant =>
                        !variant.TryGetProperty("type", out var type) || type.GetString() != "null");
                    return GetTypeName(valueSchema, definitions) + "?";
                }
            }
            return "JsonElement";
        }
        return schema.GetProperty("type").GetString() switch
        {
            "string" => "string",
            "integer" => "long",
            "number" => "decimal",
            "boolean" => "bool",
            "array" => "IReadOnlyList<" + GetTypeName(schema.GetProperty("items"), definitions) + ">",
            "object" when schema.GetProperty("additionalProperties").ValueKind == JsonValueKind.Object
                => "IReadOnlyDictionary<string, "
                   + GetTypeName(schema.GetProperty("additionalProperties"), definitions)
                   + ">",
            _ => "JsonElement",
        };
    }

    private static string ReferenceType(
        string reference,
        IReadOnlyDictionary<string, JsonElement> definitions)
    {
        var name = reference["#/$defs/".Length..];
        var schema = definitions[name];
        while (schema.TryGetProperty("$ref", out var nestedReference))
        {
            name = nestedReference.GetString()!["#/$defs/".Length..];
            schema = definitions[name];
        }
        return schema.TryGetProperty("type", out var type)
               && type.GetString() == "object"
               && schema.TryGetProperty("properties", out _)
            ? Identifier(name)
            : GetTypeName(schema, definitions);
    }

    private static string Identifier(string value)
    {
        var output = new StringBuilder();
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsAsciiLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }
            output.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }
        if (output.Length == 0) output.Append("Value");
        if (char.IsAsciiDigit(output[0])) output.Insert(0, '_');
        return output.ToString();
    }

    private static bool IsNamespace(string value)
        => !string.IsNullOrWhiteSpace(value)
           && value.Length <= 512
           && value.Split('.').All(static segment => segment.Length > 0
               && (char.IsAsciiLetter(segment[0]) || segment[0] == '_')
               && segment.All(static character => char.IsAsciiLetterOrDigit(character) || character == '_'));

    private static bool IsReferenceType(string typeName)
        => typeName == "string"
           || typeName.StartsWith("IReadOnly", StringComparison.Ordinal)
           || typeName is not ("long" or "decimal" or "bool" or "JsonElement");

    private static string Escape(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
